name: Auto Tag Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    name: Tag
    if: ${{ github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Extract version and tag
        run: |
          VERSION="${{ github.event.pull_request.head.ref }}"
          VERSION="${VERSION#release/}"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"
